apiVersion: api.my.domain/v1alpha1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: clusterscan-sontroller
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  deployment:
  - name: terrascan
    namespace: default
    recurring: true
    schedule: "*/3 * * * *"
    jobTemplate:
      name: terrascan
      image: "tenable/terrascan"
      command: ["echo"]
      args: ["'No resources to scan'"]
      restartPolicy: OnFailure
  - name: kubevious-cli
    namespace: default
    recurring: false
    jobTemplate:
      name: kubevious-cli
      image: "kubevious/cli"
      command: ["tail"]
      args: ["-f", "/dev/null"]
      restartPolicy: OnFailure